Converted all communications from serial to tcp via the ser2net proxy which now starts on boot

diff --git a/send_location_to_synscan b/send_location_to_synscan
--- a/send_location_to_synscan
+++ b/send_location_to_synscan
@@ -2,13 +2,14 @@
 
 set -e
 
-readonly serial=/dev/ttyS0
+#readonly serial=/dev/ttyS0
+timeout=5
 
 location=$(get_gps.py)
 
 if [ ${?} != 0 ]; then exit; fi
 
-stty -F ${serial} 9600
+#stty -F ${serial} 9600
 
 HEX="\\\\x%02X"
 unset FORMAT
@@ -19,6 +20,13 @@ done
 echo "Location: '${location}'"
 hex_text="$(printf "W${FORMAT}" ${location})"
 
-echo "Writing location to HC: '${hex_text}'"
-echo -ne "${hex_text}" > ${serial}
-log_info "Location $location sent to telescope"
+#echo "Writing location to HC: '${hex_text}'"
+#echo -ne "${hex_text}" > ${serial}
+RESPONSE=$(echo -ne "${hex_text}" | netcat -w $timeout -W 1 127.0.0.1 4030)
+if [ "$RESPONSE" == "#" ]; then
+	log_info "Location ${location} sent to telescope"
+	exit 0
+else
+	log_warn "Location ${location} send to delescope FAILED"
+	exit 1
+fi
diff --git a/send_time_to_synscan b/send_time_to_synscan
--- a/send_time_to_synscan
+++ b/send_time_to_synscan
@@ -2,25 +2,29 @@
 
 set -e
 
-readonly serial=/dev/ttyS0
+#readonly serial=/dev/ttyS0
 timeout=5
 
-function sendTime() {
-	# set the serial port speed
-	stty -F ${serial} 9600
+# set the serial port speed
+#stty -F ${serial} 9600
 
-	# get the date in the order the protocol calls for
-	dtm="$(date -u '+%_H %_M %_S %_m %_d %_y 0 0')"
+# get the date in the order the protocol calls for
+dtm="$(date -u '+%_H %_M %_S %_m %_d %_y 0 0')"
 
-	# H is the command char; the following 8 bytes are the date/time
-	HEX="\\\\x%02X"
-	unset FORMAT
-	for i in {1..8}; do FORMAT="${FORMAT}${HEX}"; done
-	hex_text="$(printf "H${FORMAT}" ${dtm})"
+# H is the command char; the following 8 bytes are the date/time
+HEX="\\\\x%02X"
+unset FORMAT
+for i in {1..8}; do FORMAT="${FORMAT}${HEX}"; done
+hex_text="$(printf "H${FORMAT}" ${dtm})"
 
-	echo "Writing time to HC: '${hex_text}' -> '${serial}'"
-	timeout $timeout echo -ne "${hex_text}" > ${serial}
-}
+#echo "Writing time to HC: '${hex_text}'
+#timeout $timeout echo -ne "${hex_text}" > ${serial}
+RESPONSE=$(echo -ne "${hex_text}" | netcat -w $timeout -W 1 127.0.0.1 4030)
 
-sendTime
-log_info "Time $(date) sent to telescope"
+if [ "$RESPONSE" == "#" ]; then
+	log_info "Time ${dtm} sent to telescope"
+	exit 0
+else
+	log_warn "Time ${dtm} send to delescope FAILED"
+	exit 1
+fi
